import { Router } from "express";
import { registerUser } from "./auth.controller.js";
import { loginUser } from "./auth.controller.js";
import { verifyEmail } from "./auth.controller.js";
import { changePassword } from "./auth.controller.js";
import middleware from "../../middleware/auth.middleware.js";
import { logoutUser } from "./auth.controller.js";
import { refreshToken } from "./auth.controller.js";
import { resendEmailVerification } from "./auth.controller.js";
import { protect } from "../../middleware/protect.js";
import { getMe } from "./auth.controller.js";
import { updateAdmin } from "./auth.controller.js";
import { registerStaff } from "./auth.controller.js";
const router = Router();
router.post("/register", registerUser);
router.post("/register-staff", protect, registerStaff);
router.post("/login", loginUser);
router.get("/verify-email", verifyEmail);
router.patch("/change-password", middleware, changePassword);
router.post("/logout", middleware, logoutUser);
router.post("/refresh-token", refreshToken);
router.post("/resend-email-verification", resendEmailVerification);
router.get("/get-me", protect, getMe);
router.patch("/update-admin", protect, updateAdmin);
export default router;
