import { Router } from "express";
import { processMonthlyRents } from "./rent.controller.js";
import { getRents } from "./rent.controller.js";
import { protect } from "../../middleware/protect.js";
import { sendEmailToTenantsController } from "./rent.controller.js";
const router = Router();
router.post("/process-monthly-rents", protect, processMonthlyRents);
router.get("/get-rents", protect, getRents);
router.post("/send-email-to-tenants", protect, sendEmailToTenantsController);
export default router;
